# Generated by Django 3.1.7 on 2021-03-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.IntegerField(verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('start_datetime', models.DateTimeField(db_index=True, verbose_name='Дата начала')),
                ('end_datetime', models.DateTimeField(db_index=True, verbose_name='Дата окончания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('question_type', models.IntegerField(choices=[(0, 'Text answer'), (1, 'Text answer with one choice'), (2, 'Text answer with multiple choice')])),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.poll')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.question')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=4096, null=True)),
                ('choice', models.ManyToManyField(null=True, to='rest_api.Choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rest_api.anonymoususer')),
            ],
        ),
        migrations.AddField(
            model_name='anonymoususer',
            name='answers',
            field=models.ManyToManyField(to='rest_api.Answer'),
        ),
    ]
